[package]
edition = "2024"
name = "check_translations"
version = "0.1.0"

[dependencies]
colored = "3.0"
dashmap = "6.1.0"
glob = "0.3"
lazy_static = "1.5.0"
memmap2 = "0.9.5"
rayon = "1.10.0"
regex = "1"
serde_json = "1.0"
