[package]
name = "check_translations"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0"
glob = "0.3"
regex = "1"
serde_json = "1.0"
rayon = "1.10.0"
dashmap = "6.1.0"
memmap2 = "0.9.5"
lazy_static = "1.5.0"
